# Generated by Django 2.2.25 on 2022-03-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sx_vehicle_data',
            name='category',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('B+E', 'B+E'), ('C', 'C'), ('C+E', 'C+E'), ('D1', 'D1'), ('D', 'D'), ('D+E', 'D+E')], max_length=250),
        ),
    ]
