# Generated by Django 2.2.25 on 2021-12-23 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brigade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movement_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=250)),
                ('exercise_name', models.CharField(max_length=100)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('traffic_density', models.PositiveIntegerField()),
                ('packet_gap', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_gap', models.PositiveIntegerField(blank=True, null=True)),
                # ('packet_size', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_data', to='movement.Brigade')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Route_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unit_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet_no', models.PositiveIntegerField()),
                ('vehicle_qty', models.PositiveIntegerField()),
                ('packet_allocated', models.BooleanField()),
                ('packet_auto_populted', models.BooleanField()),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_detail', to='movement.Movement_Data')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_detail', to='movement.Unit')),
            ],
            options={
                'ordering': ['packet_no'],
            },
        ),
        migrations.CreateModel(
            name='Packet_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subunit', models.CharField(max_length=50)),
                ('packet_no', models.PositiveIntegerField()),
                ('vehicle_qty', models.PositiveIntegerField()),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packet_detail', to='movement.Unit_Detail')),
            ],
            options={
                'ordering': ['packet_no'],
            },
        ),
        migrations.AddField(
            model_name='movement_data',
            name='route_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_data', to='movement.Route_Type'),
        ),
        migrations.CreateModel(
            name='CP_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_no', models.PositiveIntegerField()),
                ('diatance', models.FloatField()),
                ('halt_time', models.PositiveIntegerField()),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cp_detail', to='movement.Movement_Data')),
            ],
            options={
                'ordering': ['cp_no'],
            },
        ),
    ]
