# Generated by Django 2.2.25 on 2021-12-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brigade',
            name='acronym',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='acronym',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
