# Generated by Django 2.2.25 on 2021-12-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0002_auto_20211223_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement_data',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='acronym',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='route_type',
            name='route_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='unit',
            name='acronym',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
