# Generated by Django 2.2.25 on 2021-12-24 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0003_auto_20211223_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cp_detail',
            name='m_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cp_detail', to='movement.Movement_Data'),
        ),
        migrations.AlterField(
            model_name='packet_detail',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packet_detail', to='movement.Unit_Detail'),
        ),
        migrations.AlterField(
            model_name='unit_detail',
            name='m_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_detail', to='movement.Movement_Data'),
        ),
    ]
