# Generated by Django 2.2.25 on 2021-12-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0005_route_type_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement_data',
            name='speed',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
