# Generated by Django 2.2.25 on 2021-12-27 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0006_movement_data_speed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cp_detail',
            old_name='diatance',
            new_name='distance',
        ),
    ]
