# Generated by Django 2.2.25 on 2021-12-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0007_auto_20211227_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_detail',
            name='packet_allocated',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='unit_detail',
            name='packet_auto_populted',
            field=models.BooleanField(null=True),
        ),
    ]
