# Generated by Django 2.2.25 on 2021-12-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0008_auto_20211227_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_detail',
            name='packet_allocated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unit_detail',
            name='packet_auto_populted',
            field=models.BooleanField(default=False),
        ),
    ]
