# Generated by Django 2.2.25 on 2022-03-25 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0010_auto_20211230_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit_detail',
            old_name='packet_auto_populted',
            new_name='packet_auto_populated',
        ),
    ]
