# Generated by Django 2.2.25 on 2022-03-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0011_auto_20220325_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit_detail',
            name='packet_auto_populated',
        ),
    ]
