# Generated by Django 2.2.25 on 2022-03-15 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_by',
        ),
    ]
